# Generated by Django 3.1.2 on 2022-02-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Город')),
            ],
            options={
                'db_table': 'admin_panel_city',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Город')),
                ('profession_type', models.CharField(choices=[('med', 'Медик'), ('pacient', 'Пациент')], max_length=128, verbose_name='Тип проффесии')),
            ],
            options={
                'db_table': 'admin_panel_profession',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Юзернейм')),
                ('fullname', models.CharField(max_length=512, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.city', verbose_name='Город')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profession', verbose_name='Профессия')),
            ],
            options={
                'db_table': 'admin_panel_botuser',
            },
        ),
    ]
