# Generated by Django 3.1.2 on 2022-02-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Город')),
            ],
            options={
                'db_table': 'admin_panel_city',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('profession_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('profession_type', models.CharField(choices=[('med', 'Медик'), ('pacient', 'Пациент')], max_length=128, verbose_name='Тип проффесии')),
            ],
            options={
                'db_table': 'admin_panel_profession',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Юзернейм')),
                ('fullname', models.CharField(max_length=512, verbose_name='Имя')),
                ('profession', models.CharField(choices=[('med', 'Медик'), ('pacient', 'Пациент')], max_length=128, null=True, verbose_name='Тип проффесии')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'admin_panel_botuser',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(verbose_name='Закрыт?')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.profession', verbose_name='Направление вопроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
            options={
                'db_table': 'admin_panel_question',
            },
        ),
        migrations.CreateModel(
            name='ProfessionToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
            options={
                'db_table': 'admin_panel_profession_to_user',
            },
        ),
    ]
