# Generated by Django 3.1.2 on 2022-02-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='profession_type',
        ),
    ]
