# Generated by Django 3.1.2 on 2022-02-28 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20220228_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.profession', verbose_name='Профессия'),
        ),
    ]
