# Generated by Django 3.1.2 on 2022-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_profession_profession_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='position',
            field=models.IntegerField(default=0, null=True, verbose_name='Позиция'),
        ),
    ]
