# Generated by Django 3.1.2 on 2022-02-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_profession_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='profession',
        ),
    ]
