# Generated by Django 3.1.2 on 2022-02-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_question_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionToQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.question')),
            ],
            options={
                'db_table': 'admin_panel_profession_to_question',
            },
        ),
    ]
