# Generated by Django 3.1.2 on 2022-02-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20220228_1727'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professiontouser',
            table='admin_panel_profession_to_user',
        ),
    ]
