# Generated by Django 3.1.2 on 2022-02-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_professiontoquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response_count',
            field=models.SmallIntegerField(default=0, verbose_name='Число откликов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
        migrations.CreateModel(
            name='ChatToQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('message_id', models.BigIntegerField(verbose_name='Message ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.question')),
            ],
            options={
                'db_table': 'admin_panel_chat_to_question',
            },
        ),
    ]
