# Generated by Django 3.1.2 on 2022-03-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20220228_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='age',
            field=models.CharField(choices=[('child', 'Ребенок'), ('adult', 'Взрослый'), ('both', 'Обидва')], max_length=64, null=True, verbose_name='Возраст'),
        ),
    ]
