# Generated by Django 3.1.2 on 2022-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('med', 'Медик'), ('pacient', 'Пациент')], max_length=128, null=True, verbose_name='Тип проффесии'),
        ),
    ]
