# Generated by Django 3.1.2 on 2022-03-01 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_question_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_notification_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя 30минутная напоминалка'),
            preserve_default=False,
        ),
    ]
