# Generated by Django 3.1.2 on 2022-02-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20220228_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.profession', verbose_name='Направление вопроса'),
        ),
    ]
