# Generated by Django 3.1.2 on 2022-03-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_question_last_notification_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыт в'),
        ),
    ]
